Documentation/problem statement and goals
SumanyaG/Alkalytics pull request #22
Opened 2024-09-22 04:31 UTC by JenniferYe25

Covers Problem Statement and Goals document sections 1-3

2024-09-22 04:51 UTC, jsontran requested changes
Can you squash your commits into one following the convention and merge it into the milestone branch instead

2024-09-24 00:24 UTC, jsontran requested changes
Theres been a change in the VnV Report, if its unintentional please remove it

2024-09-24 01:33 UTC, katemin991 reviewed
- the opening statement, sections 1.1 and 1.2 don't have a lot of the changes we suggested in today's meeting, should revise the wording
- line 63 you use "labeled" and then in line 104 it's "labelled", should probably stick to one
- line 76 missing ending period
- i think we should explain who dr. de lannoy and bassel are in relation to the project. the ta/whoever reads this won't really know who they are or what they have to do with the project
- good addition of how the goals will be measured
- line 186 grammatical error, i think you meant to delete "is"
- the final sentence also does not have an ending period

2024-09-24 02:08 UTC, katemin991 requested changes
i don't think we're supposed to modify the Reflection.tex file directly. 
the reflection you wrote will be inputted into the reflection of the development plan automatically (and any other stuff that have a reflection)
the `\input{../Reflection.tex}` line (line 208) should just be removed from ProblemStatement.tex and be replaced with what you wrote in Reflection.tex!

2024-09-24 03:03 UTC, SumanyaG requested changes
For the goals section, can we number all the goals as sub-headings? I want to refer to them in the POC section and numbering would make that a lot easier.

2024-09-24 03:57 UTC, JenniferYe25 commented
> Theres been a change in the VnV Report, if its unintentional please remove it

I didn't change anything in the VnV report. I think the pdf got generated due to the common file.

2024-09-24 06:03 UTC, jsontran commented
> > Theres been a change in the VnV Report, if its unintentional please remove it
> 
> I didn't change anything in the VnV report. I think the pdf got generated due to the common file.

can you remove it from the PR then

2024-09-24 14:15 UTC, katemin991 approved these changes

2024-09-24 19:06 UTC, SumanyaG approved these changes

2024-09-24 19:51 UTC, jsontran approved these changes

2024-09-24 20:01 UTC, merged